// Mock data for the CiviLink application

import { POST_CATEGORIES, POST_STATUSES } from '../config/constants';

// ─── Mock Users ─────────────────────────────────────────────────────────────
export const mockUsers: any[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    password: 'password123',
    role: 'user',
    city: 'San Francisco',
    state: 'CA',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    points: 1250,
    badges: ['Community Guardian', 'Early Adopter', 'Top Reporter'],
    joinedDate: '2023-01-15',
    contributionScore: 1250,
    address: '123 Market St',
    zipCode: '94103',
    bio: 'Passionate about making our city better, one report at a time.',
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus.j@example.com',
    password: 'password123',
    role: 'user',
    city: 'San Francisco',
    state: 'CA',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
    points: 850,
    badges: ['Road Warrior'],
    joinedDate: '2023-03-22',
    contributionScore: 850,
    address: '456 Valencia St',
    zipCode: '94110',
    bio: 'Cyclist and transit advocate. I report potholes so you don\'t have to.',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@example.com',
    password: 'password123',
    role: 'user',
    city: 'San Francisco',
    state: 'CA',
    avatar: 'https://i.pravatar.cc/150?u=emily',
    points: 2100,
    badges: ['Super Citizen', 'Park Ranger', 'Eco Champion'],
    joinedDate: '2022-11-05',
    contributionScore: 2100,
    address: '789 Dolores St',
    zipCode: '94114',
    bio: 'Environmental advocate and community organizer in the Mission.',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.k@example.com',
    password: 'password123',
    role: 'user',
    city: 'San Francisco',
    state: 'CA',
    avatar: 'https://i.pravatar.cc/150?u=david',
    points: 430,
    badges: ['Newcomer'],
    joinedDate: '2024-01-10',
    contributionScore: 430,
    address: '321 Geary Blvd',
    zipCode: '94118',
    bio: 'New to the neighborhood, excited to help improve our community!',
  },
  {
    id: '5',
    name: 'Lisa Patel',
    email: 'lisa.p@example.com',
    password: 'password123',
    role: 'user',
    city: 'Oakland',
    state: 'CA',
    avatar: 'https://i.pravatar.cc/150?u=lisa',
    points: 670,
    badges: ['Safety First', 'Night Owl'],
    joinedDate: '2023-08-14',
    contributionScore: 670,
    address: '55 Broadway',
    zipCode: '94607',
    bio: 'Making Oakland safer for everyone.',
  },
  // Government / Admin accounts
  {
    id: 'admin-sf',
    name: 'City Administrator',
    email: 'admin@sf.gov',
    password: 'admin',
    role: 'admin',
    city: 'San Francisco',
    state: 'CA',
    department: 'Public Works',
    contributionScore: 0,
  },
  {
    id: 'admin-main',
    name: 'Main Administrator',
    email: 'civilink1357@gmail.com',
    password: 'AryanVrinda1',
    role: 'admin',
    city: 'San Francisco',
    state: 'CA',
    department: 'Central Administration',
    contributionScore: 0,
  },
];

// ─── Mock Leaders ───────────────────────────────────────────────────────────
// Fields used by LeadersPage: id, name, title, department, city, icon, email, phone
// Fields used by other components: role, approvalRating, activeInitiatives, responseRate, avatar
export const mockLeaders: any[] = [
  {
    id: 'l1',
    name: 'Mayor London Breed',
    title: 'Mayor of San Francisco',
    role: 'Mayor',
    department: 'Office of the Mayor',
    city: 'San Francisco',
    icon: '🏛️',
    email: 'mayor@sf.gov',
    phone: '(415) 554-6141',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 85,
    activeInitiatives: 12,
    responseRate: '92%',
  },
  {
    id: 'l2',
    name: 'Director David Chiu',
    title: 'City Attorney',
    role: 'City Attorney',
    department: 'City Attorney Office',
    city: 'San Francisco',
    icon: '⚖️',
    email: 'cityattorney@sf.gov',
    phone: '(415) 554-4700',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 88,
    activeInitiatives: 8,
    responseRate: '95%',
  },
  {
    id: 'l3',
    name: 'Chief William Scott',
    title: 'Chief of Police',
    role: 'Police Chief',
    department: 'Public Safety',
    city: 'San Francisco',
    icon: '🛡️',
    email: 'sfpd@sf.gov',
    phone: '(415) 553-1551',
    avatar: 'https://images.unsplash.com/photo-1556157382-97eda2d622ca?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 78,
    activeInitiatives: 15,
    responseRate: '88%',
  },
  {
    id: 'l4',
    name: 'Commissioner Sandra Fewer',
    title: 'Director of Public Works',
    role: 'Commissioner',
    department: 'Infrastructure',
    city: 'San Francisco',
    icon: '🏗️',
    email: 'publicworks@sf.gov',
    phone: '(415) 554-6920',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 82,
    activeInitiatives: 20,
    responseRate: '90%',
  },
  {
    id: 'l5',
    name: 'Director Jeffrey Tumlin',
    title: 'Director of Transportation',
    role: 'Director',
    department: 'Transportation',
    city: 'San Francisco',
    icon: '🚌',
    email: 'sfmta@sf.gov',
    phone: '(415) 701-4500',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 74,
    activeInitiatives: 18,
    responseRate: '85%',
  },
  {
    id: 'l6',
    name: 'Superintendent Phil Ginsburg',
    title: 'General Manager, Rec & Park',
    role: 'Superintendent',
    department: 'Parks & Recreation',
    city: 'San Francisco',
    icon: '🌳',
    email: 'recpark@sf.gov',
    phone: '(415) 831-2700',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 91,
    activeInitiatives: 10,
    responseRate: '93%',
  },
  {
    id: 'l7',
    name: 'Director Dr. Grant Colfax',
    title: 'Director of Public Health',
    role: 'Director',
    department: 'Health',
    city: 'San Francisco',
    icon: '🏥',
    email: 'health@sf.gov',
    phone: '(415) 554-2500',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    approvalRating: 86,
    activeInitiatives: 14,
    responseRate: '91%',
  },
];

// ─── Mock Posts ──────────────────────────────────────────────────────────────
// Covers all POST_CATEGORIES and various POST_STATUSES, for both SF and Oakland
export const mockPosts: any[] = [
  {
    id: 'p1',
    title: 'Large Pothole on Market St',
    description: 'There is a massive pothole in the eastbound lane of Market Street near 5th St. It\'s roughly 2 feet wide and causing traffic delays. Also a serious hazard to cyclists and motorcycles.',
    category: 'Infrastructure',
    status: 'in_progress',
    location: 'Market St & 5th St',
    date: '2024-02-10T10:30:00Z',
    authorId: '1',
    authorName: 'Sarah Chen',
    author: 'Sarah Chen',
    endorsements: 45,
    comments: 12,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-10T10:30:00Z', note: 'Report submitted by citizen' },
      { status: 'under_review', date: '2024-02-11T09:15:00Z', note: 'Verified by AI image analysis — confirmed Category 3 pothole' },
      { status: 'in_progress', date: '2024-02-12T14:20:00Z', note: 'Repair crew dispatched, ETA 48 hrs' },
    ],
  },
  {
    id: 'p2',
    title: 'Broken Streetlight in Mission District',
    description: 'The streetlight at the corner of Valencia and 18th has been out for three days now. The entire intersection is dangerously dark at night, especially for pedestrians.',
    category: 'Public Safety',
    status: 'pending',
    location: 'Valencia St & 18th St',
    date: '2024-02-14T19:45:00Z',
    authorId: '2',
    authorName: 'Marcus Johnson',
    author: 'Marcus Johnson',
    endorsements: 18,
    comments: 3,
    imageUrl: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-14T19:45:00Z', note: 'Report submitted' },
    ],
  },
  {
    id: 'p3',
    title: 'Trash Overflow at Dolores Park',
    description: 'The recycling bins at the south end of Dolores Park are overflowing. Trash is blowing onto the grass and attracting pests. This happens every weekend but needs a permanent solution.',
    category: 'Parks',
    status: 'completed',
    location: 'Dolores Park (south end)',
    date: '2024-02-08T16:20:00Z',
    authorId: '3',
    authorName: 'Emily Rodriguez',
    author: 'Emily Rodriguez',
    endorsements: 72,
    comments: 8,
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-08T16:20:00Z', note: 'Report submitted' },
      { status: 'under_review', date: '2024-02-09T11:00:00Z', note: 'Scheduled for cleanup crew' },
      { status: 'completed', date: '2024-02-10T13:45:00Z', note: 'Cleanup completed — extra bins added' },
    ],
  },
  {
    id: 'p4',
    title: 'Illegal Dumping on Cesar Chavez',
    description: 'A large pile of furniture and construction debris has been dumped on the sidewalk near Cesar Chavez & Guerrero. It\'s blocking pedestrian access and forcing people into the street.',
    category: 'Health',
    status: 'under_review',
    location: 'Cesar Chavez St & Guerrero St',
    date: '2024-02-13T08:15:00Z',
    authorId: '1',
    authorName: 'Sarah Chen',
    author: 'Sarah Chen',
    endorsements: 34,
    comments: 5,
    imageUrl: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-13T08:15:00Z', note: 'Report submitted with photos' },
      { status: 'under_review', date: '2024-02-13T10:30:00Z', note: 'Reviewing jurisdiction — may involve DPW and DPH' },
    ],
  },
  {
    id: 'p5',
    title: 'Graffiti on Washington High School Wall',
    description: 'Offensive graffiti was sprayed overnight on the exterior wall facing 32nd Avenue. Multiple profane and hateful messages. Students arrive in a few hours.',
    category: 'Education',
    status: 'pending',
    location: '32nd Ave & Anza St',
    date: '2024-02-15T07:30:00Z',
    authorId: '2',
    authorName: 'Marcus Johnson',
    author: 'Marcus Johnson',
    endorsements: 12,
    comments: 1,
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5b43?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-15T07:30:00Z', note: 'Urgent — report submitted before school hours' },
    ],
  },
  {
    id: 'p6',
    title: 'Bus Stop Bench Broken on Geary',
    description: 'The metal bench at the Muni bus stop on Geary & 25th is broken in half. The sharp edges are a safety hazard, especially for elderly riders who rely on it.',
    category: 'Transportation',
    status: 'in_progress',
    location: 'Geary Blvd & 25th Ave',
    date: '2024-02-11T12:00:00Z',
    authorId: '3',
    authorName: 'Emily Rodriguez',
    author: 'Emily Rodriguez',
    endorsements: 56,
    comments: 4,
    imageUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-11T12:00:00Z', note: 'Report submitted' },
      { status: 'in_progress', date: '2024-02-12T09:00:00Z', note: 'Bench replacement ordered — installation scheduled next Tuesday' },
    ],
  },
  {
    id: 'p7',
    title: 'Flooding on 19th Ave After Rain',
    description: 'Every time it rains, the intersection of 19th Ave and Judah floods badly. Water pools to knee-height, blocking crosswalks and stalling cars. Drains appear to be clogged.',
    category: 'Infrastructure',
    status: 'under_review',
    location: '19th Ave & Judah St',
    date: '2024-02-09T14:00:00Z',
    authorId: '4',
    authorName: 'David Kim',
    author: 'David Kim',
    endorsements: 63,
    comments: 9,
    imageUrl: 'https://images.unsplash.com/photo-1446034295857-c899f4c4e024?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-09T14:00:00Z', note: 'Report submitted with video evidence' },
      { status: 'under_review', date: '2024-02-10T08:30:00Z', note: 'Storm drain inspection scheduled' },
    ],
  },
  {
    id: 'p8',
    title: 'Abandoned Vehicle Blocking Bike Lane',
    description: 'A car with no plates has been parked in the bike lane on the Embarcadero near Pier 28 for over a week. Cyclists are forced into traffic to go around it.',
    category: 'Transportation',
    status: 'completed',
    location: 'Embarcadero near Pier 28',
    date: '2024-02-05T11:10:00Z',
    authorId: '2',
    authorName: 'Marcus Johnson',
    author: 'Marcus Johnson',
    endorsements: 29,
    comments: 6,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-05T11:10:00Z', note: 'Report submitted' },
      { status: 'under_review', date: '2024-02-06T09:00:00Z', note: 'SFMTA notified' },
      { status: 'in_progress', date: '2024-02-07T13:00:00Z', note: 'Tow truck dispatched' },
      { status: 'completed', date: '2024-02-07T16:30:00Z', note: 'Vehicle towed and bike lane cleared' },
    ],
  },
  {
    id: 'p9',
    title: 'Playground Equipment Damaged at Golden Gate Park',
    description: 'The children\'s playground near the Koret Children\'s Quarter has a broken swing set and a cracked slide. Several parents have reported near-misses with their kids.',
    category: 'Parks',
    status: 'in_progress',
    location: 'Golden Gate Park — Koret Quarter',
    date: '2024-02-12T09:45:00Z',
    authorId: '3',
    authorName: 'Emily Rodriguez',
    author: 'Emily Rodriguez',
    endorsements: 88,
    comments: 14,
    imageUrl: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-12T09:45:00Z', note: 'Report submitted — marked as safety concern' },
      { status: 'under_review', date: '2024-02-12T15:00:00Z', note: 'Park maintenance inspection confirmed damage' },
      { status: 'in_progress', date: '2024-02-13T10:00:00Z', note: 'Swing removed; replacement parts ordered. Slide taped off.' },
    ],
  },
  {
    id: 'p10',
    title: 'Noise Complaints — Late Night Construction',
    description: 'Construction work at the new condo development on Van Ness continues well past 10 PM nightly, violating the city noise ordinance. Multiple residents on the block are affected.',
    category: 'Public Safety',
    status: 'rejected',
    location: 'Van Ness Ave & Pine St',
    date: '2024-02-06T23:15:00Z',
    authorId: '4',
    authorName: 'David Kim',
    author: 'David Kim',
    endorsements: 41,
    comments: 7,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'San Francisco',
    statusHistory: [
      { status: 'pending', date: '2024-02-06T23:15:00Z', note: 'Report submitted' },
      { status: 'under_review', date: '2024-02-07T09:00:00Z', note: 'Forwarded to building inspection' },
      { status: 'rejected', date: '2024-02-08T14:00:00Z', note: 'Developer has valid emergency work permit for seismic retrofitting — expires March 1' },
    ],
  },
  {
    id: 'p11',
    title: 'Broken Sidewalk on Lake Merritt Path',
    description: 'Large sections of the walking path around Lake Merritt are cracked and uneven, creating trip hazards. Especially bad for joggers and people with strollers.',
    category: 'Infrastructure',
    status: 'pending',
    location: 'Lake Merritt Path (east side)',
    date: '2024-02-14T08:00:00Z',
    authorId: '5',
    authorName: 'Lisa Patel',
    author: 'Lisa Patel',
    endorsements: 22,
    comments: 2,
    imageUrl: 'https://images.unsplash.com/photo-1416169607655-0c2b3ce2e1cc?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'Oakland',
    statusHistory: [
      { status: 'pending', date: '2024-02-14T08:00:00Z', note: 'Report submitted' },
    ],
  },
  {
    id: 'p12',
    title: 'Crosswalk Signal Not Working at Grand Ave',
    description: 'The pedestrian crossing signal at Grand Avenue and Lakeshore has been stuck on "Don\'t Walk" for over 24 hours. Pedestrians are crossing against traffic blindly.',
    category: 'Transportation',
    status: 'in_progress',
    location: 'Grand Ave & Lakeshore Ave',
    date: '2024-02-13T17:30:00Z',
    authorId: '5',
    authorName: 'Lisa Patel',
    author: 'Lisa Patel',
    endorsements: 35,
    comments: 5,
    imageUrl: 'https://images.unsplash.com/photo-1517732306149-e8f829eb588a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    city: 'Oakland',
    statusHistory: [
      { status: 'pending', date: '2024-02-13T17:30:00Z', note: 'Report submitted' },
      { status: 'under_review', date: '2024-02-14T08:00:00Z', note: 'Traffic engineering notified' },
      { status: 'in_progress', date: '2024-02-14T14:00:00Z', note: 'Technician en route to diagnose' },
    ],
  },
];

// ─── Mock Notifications ─────────────────────────────────────────────────────
// Fields: id, userId, title, message, type, read, date, createdAt, relatedId
export const mockNotifications: any[] = [
  {
    id: 'n1',
    userId: '1',
    title: 'Status Update',
    message: 'Your report "Large Pothole on Market St" has been moved to In Progress. A repair crew has been dispatched.',
    type: 'status_update',
    read: false,
    date: '2024-02-12T14:20:00Z',
    createdAt: '2024-02-12T14:20:00Z',
    relatedId: 'p1',
  },
  {
    id: 'n2',
    userId: '1',
    title: 'New Endorsement',
    message: 'Your report "Large Pothole on Market St" received 5 new endorsements from community members.',
    type: 'endorsement',
    read: true,
    date: '2024-02-11T18:00:00Z',
    createdAt: '2024-02-11T18:00:00Z',
    relatedId: 'p1',
  },
  {
    id: 'n3',
    userId: '3',
    title: 'Issue Resolved',
    message: '"Trash Overflow at Dolores Park" has been marked as Completed. Extra bins were added to the area.',
    type: 'status_update',
    read: false,
    date: '2024-02-10T13:45:00Z',
    createdAt: '2024-02-10T13:45:00Z',
    relatedId: 'p3',
  },
  {
    id: 'n4',
    userId: '2',
    title: 'Comment on Your Post',
    message: 'A city official commented on "Broken Streetlight in Mission District": "We\'ve added this to the priority list."',
    type: 'comment',
    read: false,
    date: '2024-02-15T10:00:00Z',
    createdAt: '2024-02-15T10:00:00Z',
    relatedId: 'p2',
  },
  {
    id: 'n5',
    userId: '1',
    title: 'Status Update',
    message: 'Your report "Illegal Dumping on Cesar Chavez" is now Under Review by the Department of Public Works.',
    type: 'status_update',
    read: true,
    date: '2024-02-13T10:30:00Z',
    createdAt: '2024-02-13T10:30:00Z',
    relatedId: 'p4',
  },
  {
    id: 'n6',
    userId: '3',
    title: 'New Endorsement',
    message: 'Your report "Playground Equipment Damaged" has received 20 new endorsements! It\'s now a trending issue.',
    type: 'endorsement',
    read: false,
    date: '2024-02-13T16:00:00Z',
    createdAt: '2024-02-13T16:00:00Z',
    relatedId: 'p9',
  },
  {
    id: 'n7',
    userId: '2',
    title: 'Issue Resolved',
    message: '"Abandoned Vehicle Blocking Bike Lane" has been marked as Completed. Vehicle was towed.',
    type: 'status_update',
    read: true,
    date: '2024-02-07T16:30:00Z',
    createdAt: '2024-02-07T16:30:00Z',
    relatedId: 'p8',
  },
  {
    id: 'n8',
    userId: '5',
    title: 'Welcome!',
    message: 'Welcome to CiviLink! Start by browsing issues in your area or reporting a new civic concern.',
    type: 'system',
    read: true,
    date: '2024-01-10T08:00:00Z',
    createdAt: '2024-01-10T08:00:00Z',
    relatedId: null,
  },
];

// ─── Re-exports & Helpers ───────────────────────────────────────────────────
export const categories = Array.from(POST_CATEGORIES);
export const statuses = POST_STATUSES.map(s => ({ ...s }));

export const getStatusColor = (status: string) => {
  const statusObj = POST_STATUSES.find(s => s.value === status);
  return statusObj ? statusObj.color : 'text-gray-600 bg-gray-50';
};

export const getStatusLabel = (status: string) => {
  const statusObj = POST_STATUSES.find(s => s.value === status);
  return statusObj ? statusObj.label : status;
};